# variables
variable "vpc_region" {}
#variable "prying" {}
variable "project_name" {}
variable "modules_ii_vpc_cidr_block" {}
variable "modules_ii_pub_sub1_cidr_block" {}
variable "modules_ii_pub_sub2_cidr_block" {}
variable "modules_ii_priv_sub1_cidr_block" {}
variable "modules_ii_priv_sub2_cidr_block" {}
variable "modules_ii_priv_sub3_cidr_block" {}
variable "modules_ii_priv_sub4_cidr_block" {}
variable "modules_ii_pub_sub1_availability_zone" {}
variable "modules_ii_pub_sub2_availability_zone" {}
variable "modules_ii_priv_sub1_availability_zone" {}
variable "modules_ii_priv_sub2_availability_zone" {}
variable "modules_ii_priv_sub3_availability_zone" {}
variable "modules_ii_priv_sub4_availability_zone" {}
variable "modules_ii_pub_rt_cidr_block" {}
variable "modules_ii_priv_rt1_cidr_block" {}
variable "modules_ii_priv_rt2_cidr_block" {}